INSERT INTO regions (name, slug, code) VALUES
  ('Arica y Parinacota', 'arica-y-parinacota', 'AP'),
  ('Tarapacá', 'tarapaca', 'TA'),
  ('Antofagasta', 'antofagasta', 'AN'),
  ('Atacama', 'atacama', 'AT'),
  ('Coquimbo', 'coquimbo', 'CO'),
  ('Valparaíso', 'valparaiso', 'VS'),
  ('Región Metropolitana de Santiago', 'region-metropolitana', 'RM'),
  ('O''Higgins', 'ohiggins', 'LI'),
  ('Maule', 'maule', 'ML'),
  ('Ñuble', 'nuble', 'NB'),
  ('Biobío', 'biobio', 'BI'),
  ('La Araucanía', 'la-araucania', 'AR'),
  ('Los Ríos', 'los-rios', 'LR'),
  ('Los Lagos', 'los-lagos', 'LL'),
  ('Aysén', 'aysen', 'AI'),
  ('Magallanes y la Antártica Chilena', 'magallanes', 'MA')
ON CONFLICT (code) DO NOTHING;
-- Comunas de la Región Metropolitana (52 comunas)
-- region_id = 7 (RM)
INSERT INTO communes (region_id, name, slug) VALUES
  (7, 'Santiago', 'santiago'),
  (7, 'Providencia', 'providencia'),
  (7, 'Las Condes', 'las-condes'),
  (7, 'Vitacura', 'vitacura'),
  (7, 'Lo Barnechea', 'lo-barnechea'),
  (7, 'Ñuñoa', 'nunoa'),
  (7, 'La Reina', 'la-reina'),
  (7, 'Macul', 'macul'),
  (7, 'Peñalolén', 'penalolen'),
  (7, 'La Florida', 'la-florida'),
  (7, 'Puente Alto', 'puente-alto'),
  (7, 'San Joaquín', 'san-joaquin'),
  (7, 'San Miguel', 'san-miguel'),
  (7, 'La Cisterna', 'la-cisterna'),
  (7, 'El Bosque', 'el-bosque'),
  (7, 'San Bernardo', 'san-bernardo'),
  (7, 'Maipú', 'maipu'),
  (7, 'Estación Central', 'estacion-central'),
  (7, 'Cerrillos', 'cerrillos'),
  (7, 'Pedro Aguirre Cerda', 'pedro-aguirre-cerda'),
  (7, 'Lo Espejo', 'lo-espejo'),
  (7, 'Recoleta', 'recoleta'),
  (7, 'Independencia', 'independencia'),
  (7, 'Conchalí', 'conchali'),
  (7, 'Huechuraba', 'huechuraba'),
  (7, 'Quilicura', 'quilicura'),
  (7, 'Renca', 'renca'),
  (7, 'Cerro Navia', 'cerro-navia'),
  (7, 'Lo Prado', 'lo-prado'),
  (7, 'Quinta Normal', 'quinta-normal'),
  (7, 'Pudahuel', 'pudahuel'),
  (7, 'La Granja', 'la-granja'),
  (7, 'San Ramón', 'san-ramon'),
  (7, 'La Pintana', 'la-pintana'),
  (7, 'Colina', 'colina'),
  (7, 'Lampa', 'lampa'),
  (7, 'Buin', 'buin'),
  (7, 'Paine', 'paine'),
  (7, 'Peñaflor', 'penaflor'),
  (7, 'Talagante', 'talagante'),
  (7, 'Melipilla', 'melipilla'),
  (7, 'San José de Maipo', 'san-jose-de-maipo'),
  (7, 'Pirque', 'pirque'),
  (7, 'Calera de Tango', 'calera-de-tango'),
  (7, 'Padre Hurtado', 'padre-hurtado'),
  (7, 'El Monte', 'el-monte'),
  (7, 'Isla de Maipo', 'isla-de-maipo'),
  (7, 'Curacaví', 'curacavi'),
  (7, 'María Pinto', 'maria-pinto'),
  (7, 'San Pedro', 'san-pedro'),
  (7, 'Alhué', 'alhue'),
  (7, 'Tiltil', 'tiltil')
ON CONFLICT (slug) DO NOTHING;
