[gcp_service_account]
type = "service_account"
project_id = "analizador-bancos"
private_key_id = "db0f80519209426492009857305890aa22910447"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcSIQETV+JnVG8
6fbjVc5y0MfaeBO1Qab2fx3/LTNVk4rod+dWMEp56lmeWPfQ605+BOSzVLc2BXn3
DupXJRjWoXBPtphqa2FHE4SO4lITF1jofolc7Sj/LFhkp8jlCJ+XzYYEllMSf6jR
VYXnLxD0ZH5ZkUiQ74OHEyRSzSEe1ykDhrJqKxGqCKtKDleTSZcCoJ9dixpYTxZK
fGXH1a5t+8CU3lJohN6cnG4auKymmK3DPy2/YpKF9GtC+285X53H4HWl+CJFzEmM
X5Tkat9vt1Kgp2SiHzJtFx9t5oq1brVwVXfdVaji9BDnX2N04+2GtrNDyqCmv7RL
OLppYquTAgMBAAECggEAQq230cQXSnYaLTFfemAeTKNiWYZY1kFUFKBosnpdCBqC
riuWQpIo/Hot0V8hIHx8yUyaLR8safqNLokpF5RG1DAd5IzB28nDv9kGehX6sZWJ
A+0U+1ZeYvzPG+bwUjPLL6/rCaL/f4mDBAlqr5fHspX7yIgxf1EJe4SBv2gwxOCa
MGoTGMB1nrhCgVwN4VXMBV0/4GPOC5sezZ6GTIB3e5wpb0XBmHvVyNKqTQLalP5u
xIwJnpoFk9mbr5CjRAmOG+yrE7MB3J4vnqz46s0lqudFUCwxvzJVFzUya1nAluh6
94B71vbar8AvBkPU5GjFenXKTsdSJcgJHmT5QGlHTQKBgQDMf2lgJDbjD0T2xuDO
pXRG66ddvOgcgExX3IY+IWOJ8ltZnebi/GPW1q3QR1hHkNEvt3YOHxlSZ1rNbOGH
Udel2VBMkCodpmYj1Eo8WsrGY4akk8CW4Gl1eDsj52p7J9ENMD0osig1d1iBqmw6
uhQ8HqoFbU8AS/G64+rysepmnQKBgQDDpJKgHCBtSk2NUkmI3IOcaHa77w5Vz2TY
ZZJ4nI4473ubJr8/3eZZxJUGVouSMy6NhgRnTYYxKlAQ4dAIOeLRDtxqixJO1xKl
wl5h8A985FGZ05fOhIAd2k96MMPiwjobTED72G3I6IobUkrhbMcm6O7PwOgsjRWp
i7ktQGqr7wKBgEAjeh5wXVKr+FpaGCpYFHcl9DFfTYGa79bi0Kvt9vVOMT6TWtY4
iOvaG1vm9JZFooaPyRQ2xs9koUMq8jVqAvP+i8Pnt33jMcftDneNlmnQz2sQ+GeZ
7Rmt4waoz2nfHB9B0PzRm/DhBL5ugFGPCUet6m+XUB7sst2GHKuQB8+1AoGAETgC
z6SqFfRcLvv3DNybmMB48sFveY3vSjxmT8c3nTs2nckjO/PDulLa6tvjHNL0XfBV
ouHn1ZvrwBCfxpmRpOSx8Y6b5eR3967Lr8L5GfzeUbOVwM9Yl0gHhrGUC/kcNBrZ
/VBnGS+eOBleDckNHheSLSbFSGaCaZGqkpkAynECgYBgtkurGdOhauu7ip5XEnBz
7+8ry1GcPg4HgjstOFmR6FHGiFuI1E9uK5YX5rDkdx0tmRlU2e+RnvqwfGrvQK6D
7+oYIyDxgzegvyH2tFTHkmxdGm4wOG7CF8t7k9ZESSz1dji/w71XyQdVwyFTTt4N
q0GG/QUz9Oip183tLKZSDg==
-----END PRIVATE KEY-----
'''
client_email = "bank-processor@analizador-bancos.iam.gserviceaccount.com"
client_id = "100378242524535518221"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bank-processor%40analizador-bancos.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[splitwise]
api_key = "jcmC5A18IiTQYagxJ9EmkFDAV3MQOryYw3c0PC8h"